AWSTemplateFormatVersion: "2010-09-09"
Description: IAM resource
Parameters:
  Name:
    Description: 'Resource name of CloudFormation Stack'
    Type: String
    Default: 'simplydemo'
  Owner:
    Description: 'Enter the email of the Owner who will operate the CloudFormation stack.'
    Type: String
    Default: 'your@email.com'
  Team:
    Description: 'Team name that will operate the CloudFormation stack.'
    Type: String
    Default: DevOps
  AwsRegion:
    Description: 'Choose the AWS Region code where you want to deploy artifact.'
    Type: String
    Default: ap-northeast-2
    AllowedValues:
      - ap-northeast-1
      - ap-northeast-2
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-central-1
      - eu-north-1
      - eu-south-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - me-south-1
      - me-central-1
  GitHubOrgName:
    Description: 'Github organization or account name under which Github Actions run.'
    Type: String
    Default: 'simplydemo'
  RepositoryName:
    Description: 'ECR repository name where you want to upload docker image.'
    Type: String
    Default: 'simplydemo'
  EKSClusterName:
    Description: 'EKS cluster name for accessing by api like kubectl'
    Type: String
    Default: 'nova-an2d-demo-eks'
  ArtifactS3Bucket:
    Description: 'Enter the S3 Bucket name where you want to upload artifact.'
    Type: String
    Default: 'simplydemo-artifact-s3'
  RoleMaxSessionDuration:
    Description: 'The maximum session duration (in seconds) limits the role-duration-seconds value in aws-actions/configure-aws-credentials'
    Type: Number
    MinValue: 3600
    MaxValue: 43200
    Default: 21600

Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1b511abead59c6ce207077c0bf0e0043b1382612

  GitHubActionsRole:
    Type: AWS::IAM::Role
    DependsOn:
      - GithubOidc
    Properties:
      RoleName:
        Fn::Join:
          - ''
          - - Ref: Name
            - 'GithubActionsRole'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub repo:${GitHubOrgName}/*:*
      MaxSessionDuration: !Ref RoleMaxSessionDuration
      Policies:
        - PolicyName:
            Fn::Join:
              - ''
              - - Ref: Name
                - 'GithubActionAccessPolicy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: GetTokenForECR
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Sid: AccessForECR
                Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - ecr:ListImages
                Resource:
                  - !Sub arn:aws:ecr:${AwsRegion}:${AWS::AccountId}:repository/${RepositoryName}
                  - !Sub arn:aws:ecr:${AwsRegion}:${AWS::AccountId}:repository/${RepositoryName}/*
              - Sid: AccessForEKS
                Effect: Allow
                Action:
                  - eks:DescribeCluster
                Resource:
                  - !Sub arn:aws:eks:${AwsRegion}:${AWS::AccountId}:cluster/${EKSClusterName}
        - PolicyName:
            Fn::Join:
              - ''
              - - Ref: Name
                - 'GithubActionDeployPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codedeploy:Get*'
                  - 'codedeploy:Batch*'
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:RegisterApplicationRevision'
                  - 'codedeploy:List*'
                Resource:
                  - !Sub 'arn:${AWS::Partition}:codedeploy:*:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - 's3:putObject'
                Resource: !Sub arn:${AWS::Partition}:s3:::${ArtifactS3Bucket}/*
      Tags:
        - Key: ManagedBy
          Value: CF
        - Key: Name
          Value:
            Fn::Join:
              - ''
              - - Ref: Name
                - 'GithubActionsRole'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default:
            Resource Name
        Parameters:
          - Name
      - Label:
          default: Ownership
        Parameters:
          - Owner
          - Team
      - Label:
          default: OIDC Integration Settings
        Parameters:
          - GitHubOrgName
          - AwsRegion
          - RepositoryName
          - ArtifactS3Bucket
          - RoleMaxSessionDuration
    ParameterLabels:
      Name:
        default: 'Enter the resource name of the CloudFormation stack'
      Owner:
        default: 'Enter the owner email address that manages the CloudFormation stack'
      Team:
        default: 'Enter team name that operating the CloudFormation stack'
